const express=require('express');
const router=express.Router();
var bodyParser = require('body-parser');
var jsonParser = bodyParser.json();
const productController=require('../controllers/productController');
router.get('/fetchProducts',jsonParser,productController.fetchProducts);
router.post('/create',jsonParser,productController.createProduct);
router.post('/update',jsonParser,productController.updateQuantity);
router.post('/updateProduct',jsonParser,productController.updateProduct);
router.delete('/delete/:id',jsonParser,productController.deleteProduct);
router.get('/search',productController.productSearch);
module.exports=router;